add -x flag to enable cc flags
cznic/99c pull request #3
Opened 2017-10-09 14:10 UTC by mattn

This is suggestion based pull-request. I want to compile code with c11 features.

See https://github.com/cznic/99c/issues/2

So I added flag `-x` to enable some flags of cc.

2017-10-09 14:26 UTC, cznic requested changes
Thanks for the PR. I like the approach of doing all the cc options at once in one PR very much, kudos for that!

Please see the inliine comments for requested changes, thank you.

2017-10-09 14:26 UTC, cznic commented on main.go
> +		case arg == "-x":
Please find a flag name that is not used by gcc, it uses -x for settin the language of the next argument. That's why I started to use "silly" flag names like '-99lib'. The long term goal is to be able to do somehting like `CC=99c ./configure && make`, so we must avoid using existing gcc flags.

2017-10-09 14:26 UTC, cznic commented on main.go
> +			a.opts = append(a.opts, a.extra(arg[2:]))
I think we need to replace this line by

```go
if i+1 >= len(args) {
	exit(2, "missing -x argument") // Note the name of '-x' has yet to be detrmined
}

a.opts = append(a.opts, a.extra(arg[i+1]))
arg[i+1] = ""
```

2017-10-09 16:35 UTC, cznic requested changes
Two last small changes please.

2017-10-09 16:35 UTC, cznic commented on main.go
> +				exit(2, "missing -99flag argument")
s/flag/extra/

2017-10-09 16:39 UTC, cznic requested changes
Update of my previous review.

2017-10-09 16:39 UTC, cznic commented on main.go
> +  -xEXTRA
Somehow one comment got lost, sorry

s/-xEXTRA/-99extra argument/

2017-10-09 17:22 UTC, cznic approved these changes
LGTM, please merge to master branch, thank you.

2017-10-10 07:48 UTC, merged

2017-10-10 07:51 UTC, mattn commented
Thank you